### ISSUE TITLE
Attribuut gemeentenaam zowel als rdfs-label & eigen term in Adresregister AP

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-toolchain#1]
Zelfde label "gemeentenaam" wordt 2x verschillend gebruikt in het Adresregister AP:

http://data.vlaanderen.be/doc/applicatieprofiel/adresregister#Adresvoorstelling
gemeentenaam = http://data.vlaanderen.be/ns/adresregister#gemeentenaam

http://data.vlaanderen.be/doc/applicatieprofiel/adres#Gemeentenaam
gemeentenaam = http://www.w3.org/2000/01/rdf-schema#label

**Comment by mvanbrab** [comment]
Update links in de originele post:
https://data.vlaanderen.be/doc/applicatieprofiel/adresregister/#Adresvoorstelling
https://data.vlaanderen.be/doc/applicatieprofiel/adresregister/#Gemeentenaam

**Comment by bertvannuffelen** [comment]
opgelost.

**Comment by GeertThijs** [comment]
Opgelost op welke manier?

**Comment by bertvannuffelen** [comment]
Dit heeft te maken met de json-ld disambiguatie van termen. In een nieuwe contextfile zullen de termen volledig gedisambigueerd zijn.

**Comment by mvanbrab** [comment]
Getest op otl-test in publicatie met deze urlref: /doc/applicatieprofiel/adressenregister/ontwerpdocument/niet-bepaald.
Is OK na laatste aanpassing toolchain op otl-test (zie #41)
