### ISSUE TITLE
"Specialisatie van" staat er altijd

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO-toolchain#18]
**Link waar het probleem zich voor doet:**
In html gegenereerd door toolchain 2.0, bv: https://otl-test.data.vlaanderen.be/ns/generiek/ontwerpdocument/01-07-2019

**Omschrijving van het probleem:**
Ook als een klasse niet overerft van een andere klasse is er een entry "specialisatie van" in de beschrijving vd klasse, bv:
![image](https://user-images.githubusercontent.com/22620291/60759680-852e0600-a029-11e9-9c06-69b0e8f1296f.png)
In toolchain voor 2.0 was dit wel correct. 

**Omschrijving van een mogelijke oplossing:**
Oorspronkelijke aanpak herstellen.

**Comment by mvanbrab** [comment]
Merk op: is blijkbaar ooit tussendoor eens opgelost geweest, maar is nu weer zoals gemeld.
Zie ook https://github.com/bertvannuffelen/demo_oslodoc/issues/9.

**Comment by mvanbrab** [comment]
**Oplossing hiervoor te doen in de vocabularium template in de config dir van je thema repository.
Uit https://github.com/bertvannuffelen/demo_oslodoc/issues/9:** 

_Dit komt voor als in de template voor het vocabularium een verkeerde basis template wordt gekozen. Aanpassen naar:
**{% extends "voc2.j2" %}**
lost het probleem op._

_Hint voor de toolchain deployment: de verkeerde (oude) basistemplate niet meer ter beschikking stellen, zodat de toolchain stopt met een foutmelding._
