### ISSUE TITLE
In AP's niet duidelijk dat bepaalde klassen ook de eigenschappen van andere klassen overerven en dus de bijhorende regels

### ISSUE THREAD

**Issue by laurensdv** [Informatievlaanderen/OSLO-toolchain#2]
In AP's niet duidelijk dat bepaalde klassen ook de eigenschappen van andere klassen overerven en dus de bijhorende regels.

zie bvb. de documentatie van Organisatie en GeregistreerdeOrganisatie.

http://data.vlaanderen.be/doc/applicatieprofiel/organisatie#GeregistreerdeOrganisatie
en 
http://data.vlaanderen.be/doc/applicatieprofiel/organisatie#Organisatie

**Comment by mvanbrab** [comment]
Update links in de originele post:
https://data.vlaanderen.be/doc/applicatieprofiel/organisatie-basis/#Geregistreerde%20Organisatie
https://data.vlaanderen.be/doc/applicatieprofiel/organisatie-basis/#Organisatie

**Comment by mvanbrab** [comment]
Toevoeging van **Subklasse van** in de output voor applicatieprofielen lost dit op.
