### ISSUE TITLE
Contextfile gaat uit van embedding

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO-toolchain#24]
**Link waar het probleem zich voor doet:** Bvb https://data.vlaanderen.be/context/persoon-basis.jsonld.

**Omschrijving van het probleem:** JSON-LD voorziet twee manieren om naar klassen of complexe datatypes te verwijzen: referencing of embedding.
Vb van referencing:
```
  "@graph": [
    {
      "@id": "https://api-gw.antwerpen.be/digipolis/persoon/v6/persons/00000014183",
      "@type": "Persoon",
...
     "heeftGeboorte": "_:b1",
...
    },
    {
      "@id": "_:b1",
      "@type": "Geboorte",
      "datum": "1932-07-12T00:00:00.000",
      "plaats": "https://data.vlaanderen.be/id/plaats/123",
...
    },
    {
      "@id": "https://data.vlaanderen.be/id/plaats/123",
      "@type": "Plaats",
      "plaatsnaam": "Ertvelde"
    },
...
  ]
```
Bv naar de plaats "Ertvelde" wordt in heeftGeboorte verwezen dmv een id. De betrokken plaats wordt verderop in de graph toegevoegd. Dit laat hergebruik toe in andere instanties van Persoon, ttz "Ertvelde" moet maar 1 keer beschreven te worden in de uitgewisselde data.
Vb van embedding:
```
  "@graph": [
    {
      "@id": "https://api-gw.antwerpen.be/digipolis/persoon/v6/persons/00000014183",
      "@type": "Persoon",
...
      "heeftGeboorte": {
        "@type": "Geboorte",
        "datum": "1932-07-12T00:00:00.000",
        "plaats": {
          "@type": "Plaats",
          "plaatsnaam": "Ertvelde"
        },
...
      },
...
    }
  ]
```

In de huidige contextfile is enkel embedding voorzien, de context voor bv plaats is:
```
	"plaats":{
	 "@id":"https://data.vlaanderen.be/ns/persoon#plaats",
	 "@type":"http://purl.org/dc/terms/Location"
	},
```

Er is een eenvoudige workaround hiervoor in de graph door de string die bv plaats identificeert aan te duiden met @id:

```
  "@graph": [
    {
      "@id": "https://api-gw.antwerpen.be/digipolis/persoon/v6/persons/00000014183",
      "@type": "Persoon",
...
      "heeftGeboorte": { "@id": "_:b1" },
...
    },
    {
      "@id": "_:b1",
      "@type": "Geboorte",
      "datum": "1932-07-12T00:00:00.000",
      "plaats": { "@id": "https://data.vlaanderen.be/id/plaats/123" },
...
    },
    {
      "@id": "https://data.vlaanderen.be/id/plaats/123",
      "@type": "Plaats",
      "plaatsnaam": "Ertvelde"
    },
...
  ]
```
Maar een aangepaste contextfile zou eenvoudiger zijn, de oorspronkelijke JSON moet dan minder worden aangepast.

**Omschrijving van een mogelijke oplossing:**
Aanpassing vd contextfile door in dergelijke gevallen @id op te geven als waarde voor @type, vb:
```
      "plaats": {
        "@id": "https://data.vlaanderen.be/ns/persoon#plaats",
        "@type": "@id"
      }
```
Toepassing: Op attributen die een associatie met een klasse voorstellen, NIET voor attributen met een complex datatype.

**Comment by GeertThijs** [comment]
Vraag was om dit enkel toe te passen "Op attributen die een associatie met een klasse voorstellen, NIET voor attributen met een complex datatype." (zie hoger). Bv voor Mobiliteitsdienst.resource in https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/mobiliteit-trips-en-aanbod/kandidaatstandaard/2020-04-09/context/mobiliteit-trips-en-aanbod-ap.jsonld staat nu
```
    "Mobiliteitsdienst.resource": {
      "@container": "@set",
      "@id": "https://data.vlaanderen.be/ns/mobiliteit/trips-en-aanbod#mobiliteitsdienst.resource",
      "@type": "@id"
    },
 ```
wat inderdaad is zoals verwacht (referencing). Maar voor Mobiliteitsdienst.beschikbaarheid verwacht ik embedding:
```
    "Mobiliteitsdienst.beschikbaarheid": {
      "@container": "@set",
      "@id": "https://data.vlaanderen.be/ns/mobiliteit/trips-en-aanbod#Mobiliteitsdienst.beschikbaarheid",
      "@type": "https://data.vlaanderen.be/ns/mobiliteit/trips-en-aanbod#Beschikbaarheid"
    },
``` 
want Beschikbaarheid is een complex datatype.

**Comment by bertvannuffelen** [comment]
Jsonld maakt geen onderscheid tussen een complex datatype of een normaal object, net zoals RDF. Het maakt onderscheid tussen literals en resources. En complexe datatypes zijn dus resources. 

In json-ld terminology betekend `@id` niet het heeft een semantische identifier, maar het betekent het is een referentie naar een complex object waarvoor de naamgevingregels gelden. 

Zie de voorbeelden in https://github.com/SEMICeu/DCAT-AP/issues/59.

Het onderstaande voorbeeld 

```
{ "@context" : {
 "mobiliteitsdienst.beschikbaarheid": {
      "@container": "@set",
      "@id": "https://data.vlaanderen.be/ns/mobiliteit/trips-en-aanbod#Mobiliteitsdienst.beschikbaarheid",
      "@type": "https://data.vlaanderen.be/ns/mobiliteit/trips-en-aanbod#Beschikbaarheid"
    },
  "attr1" : "https://test.com/1"
},
 "@id" : "https://test.com/1",
 "mobiliteitsdienst.beschikbaarheid" : [
   { "attr1" : "1"}, "https://test.com/beschikbaarheid/1"
  ]
}
```

toont aan dat indien voor eender welke reden dan ook er toch een identifier zou gebruikt worden dit leidt tot een volkomen foutieve struktuur.
`@type` in json-ld kan enkel gespecifieerd worden voor literals. 

Ik wil vermijden dan we context files maken waarbij het met een triviale editing aan de data kant er volkomen foutieve uitkomst komt.

**Comment by GeertThijs** [comment]
Oké, ik begrijp het voorbeeld niet echt, zal je mij eens mondeling moeten toelichten. Voor de rest: in de vorige versie werd "@type":"@id" nergens toegepast. Dus dit is wel een verbetering?
