### ISSUE TITLE
Foute jsonld link in AP spec

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO-toolchain#25]
**Link waar het probleem zich voor doet:** 
Vb https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/generiek-basis/zonderstatus/20190701#jsonld.

**Omschrijving van het probleem:**
Huidige link in de spec:
![image](https://user-images.githubusercontent.com/22620291/65443981-6290d980-de2f-11e9-8e49-84d71b24a36a.png)
De link klopt niet want publicatie vindt plaats op https://otl-test.data.vlaanderen.be, niet op https://data.vlaanderen.be.
Maw we verwachten eerder deze (relatieve) link: 
/doc/applicatieprofiel/generiek-basis/zonderstatus/20190701/context/generiek-basis.jsonld.

**Omschrijving van een mogelijke oplossing:**
Toolchain aanpassen.

**Comment by bertvannuffelen** [comment]
template aanpassen met absolute link in tekst.

**Comment by bertvannuffelen** [comment]
Oplossing zie  commit https://github.com/Informatievlaanderen/OSLOthema-Generiek/commit/9f3789de4524780a1cbb8176fbc500d711f69049
