### ISSUE TITLE
toolchain > ongewenste omvorming naar kleine letter op eerste karakter uit name tag op een rol

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLO-toolchain#29]
**Link waar het probleem zich voor doet:
Bijvoorbeeld (niet de enige)
https://otl-test.data.vlaanderen.be/ns/mobiliteit/trips-en-aanbod
Zoek hier naar de eigenschap met uri
https://data.vlaanderen.be/ns/mobiliteit/trips-en-aanbod#vervoersbewijs.dienst

**Omschrijving van het probleem:** 
De uri zou moeten zijn
https://data.vlaanderen.be/ns/mobiliteit/trips-en-aanbod#Vervoersbewijs.dienst
(met hoofdletter V na de #)
De code doet een tolower1() op de eerste letter van de name tag van de rol, wat ongewenst is.

**Omschrijving van een mogelijke oplossing:**
Code fiks.

Zie ook deze issue: https://github.com/bertvannuffelen/demo_oslodoc/issues/27

**Comment by bertvannuffelen** [comment]
@mvanbrab: Zie https://otl-test.data.vlaanderen.be/doc/vocabularium/mobiliteit-trips-en-aanbod/kandidaatstandaard/2020-04-09/

volgens mij is het toch ok voor deze?

**Comment by mvanbrab** [comment]
@bertvannuffelen
Nope, er staat nog altijd https://data.vlaanderen.be/ns/mobiliteit/trips-en-aanbod#vervoersbewijs.dienst zoals in de originele post van dit issue (met kleine v dus).

Dit issue gaat overigens alleen over name tags op **rollen**.
Het oorspronkelijke issue bertvannuffelen/demo_oslodoc#27 (ook vermeld bovenaan dit issue) is zelfs nog breder en gaat over tags op **rollen** en **associaties**.
Ik heb ook de publicaties die in het oorspronkelijke issue verwezen worden opnieuw laten genereren en ze bevatten ook nog dezelfde fouten.
