### ISSUE TITLE
toolchain - Fout in rendering 'Status van dit document': 'Onbekend'

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLO-toolchain#35]
Voor een applicatieprofiel met status https://data.vlaanderen.be/id/conceptscheme/StandaardStatus/OntwerpStandaard genereert de toolchain iets als dit, waarin 'Onbekend' fout is:

![afbeelding](https://user-images.githubusercontent.com/6448245/75246539-445d4a00-57d0-11ea-9083-bba01c604cbc.png)

Zie ook bijvoorbeeld https://otl-test.data.vlaanderen.be/doc/applicatieprofiel/perceel/tijdens-aanpassingen-kandidaat-standaard.

**Comment by bertvannuffelen** [comment]
De oorzaak hiervan is dat de URI van de status incorrect was ingegeven. Martin heeft dit gedetecteerd op 31/03 en aangepast. Bij een nieuwe rerun, zouden de meeste issues hiervan moeten opgelost zijn.

**Comment by bertvannuffelen** [comment]
net gechecked op test. Is opgelost.
Ik heb ook nog de tekst iets aangepast in de basis-template, maar die is nog niet gedeployed.
