### ISSUE TITLE
Fout in de tekst bij de SHACL link in applicatieprofielen

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLO-toolchain#63]
**Link naar een voorbeeld waar het probleem zichtbaar is**
https://test.data.vlaanderen.be/doc/applicatieprofiel/DCAT-AP-VL#shacl

**Omschrijving van het probleem**
De href is correct, maar de tekst toont verkeerdelijk
doc/applicatieprofiel/DCAT-AP-VL/standaard/2019-06-13/**context**/DCAT-AP-VL-SHACL.ttl
/DCAT-AP-VL-SHACL.ttl

**Omschrijving van een mogelijke oplossing**
Pas aan (context --> shacl), bijvoorbeeld
doc/applicatieprofiel/DCAT-AP-VL/standaard/2019-06-13/**shacl**/DCAT-AP-VL-SHACL.ttl
/DCAT-AP-VL-SHACL.ttl

**Comment by mvanbrab** [comment]
Duplicate van #26

**Comment by bertvannuffelen** [comment]
opgelost in template SPEC-generator. Nog niet gedeployed.

**Comment by GeertThijs** [comment]
Inderdaad momenteel niet zichtbaar. Later nog eens testen.

**Comment by mvanbrab** [comment]
Getest op test-feature-checkout branch en daar nu OK.
