### ISSUE TITLE
Verkeerd domein in de URL bij "Deze versie"

### ISSUE THREAD

**Issue by mvanbrab** [Informatievlaanderen/OSLO-toolchain#64]
**Link naar een voorbeeld waar het probleem zichtbaar is**
https://test.data.vlaanderen.be/doc/applicatieprofiel/DCAT-AP-VL

**Omschrijving van het probleem**
Er staat https://otl-test.data.vlaanderen.be/...

**Omschrijving van een mogelijke oplossing**
Aanpassen naar
https://test.data.vlaanderen.be/...
https://data.vlaanderen.be/...

**Comment by bertvannuffelen** [comment]
fix gecommit. -> toolchain zal alles herbuilden.

**Comment by bertvannuffelen** [comment]
opgelost

**Comment by GeertThijs** [comment]
Opgelost op test, niet op dev.

**Comment by mvanbrab** [comment]
Geen probleem op dev, Geert. Met "dev" bedoelt Bert de branch "test-feature-checkout" en deze publiceert op https://otl-test.data.vlaanderen.be/..., dus daar is het domein wel correct...
