### ISSUE TITLE
foaf:Person is met hoofdletter

### ISSUE THREAD

**Issue by dimi-schepers** [Informatievlaanderen/OSLO-toolchain#69]
Zie [https://github.com/Informatievlaanderen/OSLO-Discussion/issues/333](https://github.com/Informatievlaanderen/OSLO-Discussion/issues/333)

**Comment by mvanbrab** [comment]
@dimi-schepers : dit is toch geen toolchain-related issue?

**Comment by dimi-schepers** [comment]
Lijkt inderdaad opgelost te zijn in nieuw gegenereerde VOCs.
